// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HUo0kTK5o_bpVGSECi40ckm9gA-PtMc',
    appId: '1:483104044980:web:4990522d2eeb223cc724e1',
    messagingSenderId: '483104044980',
    projectId: 'uniride-gsu',
    authDomain: 'uniride-gsu.firebaseapp.com',
    storageBucket: 'uniride-gsu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mpe0sYud3yXcqHX1v-Lp5siQ4qXEI_4',
    appId: '1:483104044980:android:0bebacb0e7203db0c724e1',
    messagingSenderId: '483104044980',
    projectId: 'uniride-gsu',
    storageBucket: 'uniride-gsu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYBGFFpXjfBkQTGA3jueZE1aT_KgHxHqE',
    appId: '1:483104044980:ios:2cd942b67656dbfec724e1',
    messagingSenderId: '483104044980',
    projectId: 'uniride-gsu',
    storageBucket: 'uniride-gsu.firebasestorage.app',
    iosBundleId: 'com.example.uniride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYBGFFpXjfBkQTGA3jueZE1aT_KgHxHqE',
    appId: '1:483104044980:ios:2cd942b67656dbfec724e1',
    messagingSenderId: '483104044980',
    projectId: 'uniride-gsu',
    storageBucket: 'uniride-gsu.firebasestorage.app',
    iosBundleId: 'com.example.uniride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HUo0kTK5o_bpVGSECi40ckm9gA-PtMc',
    appId: '1:483104044980:web:0b2ab9766625d927c724e1',
    messagingSenderId: '483104044980',
    projectId: 'uniride-gsu',
    authDomain: 'uniride-gsu.firebaseapp.com',
    storageBucket: 'uniride-gsu.firebasestorage.app',
  );
}
